import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { Box } from 'components/Box'
import { CastAvatar } from 'components/CastAvatar'
import { H4 } from 'components/Heading'
import { Text } from 'components/Text'
import { Skeleton } from 'components/Skeleton'

export const CastSkeleton = () => {
  return (
    <Box>
      <CastAvatar mb={4} />
      <Skeleton height={16} mb={4} width='100%' />
      <Skeleton height={12} mb={2} width='64%' />
    </Box>
  )
}

export const Cast = ({
  className,
  image,
  name,
  role,
  ...restOfProps
}) => {
  return (
    <Box
      className={className}
      {...pick(restOfProps)}
    >
      <CastAvatar
        alt={name}
        mb={4}
        src={image}
      />
      {name && <H4>{name}</H4>}
      {role && (
        <Text
          color='neutral.4'
          fontSize={0}
          lineHeight={0}
        >
          {role}
        </Text>
      )}
    </Box>
  )
}

Cast.propTypes = {
  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Image path for cast avatar
   */
  image: PropTypes.string,

  /**
   * Name of the cast member
   */
  name: PropTypes.string,

  /**
   * Role of the cast member
   */
  role: PropTypes.string
}
