import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { Image } from 'components/Image'
import { StyledCastAvatar } from './CastAvatar.styles'

export const CastAvatar = ({ alt, className, src, ...restOfProps }) => {
  return (
    <StyledCastAvatar
      className={className}
      {...pick(restOfProps)}
    >
      {src && (
        <Image
          alt={alt}
          left={0}
          position='absolute'
          top={0}
          src={src}
        />
      )}
    </StyledCastAvatar>
  )
}

CastAvatar.propTypes = {
  /**
   * Alt tag used to describe image when it fails to load
   */
  alt: PropTypes.string,

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Cast avatar image path
   */
  src: PropTypes.string
}
