import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { StyledCertificationBadge } from './CertificationBadge.styles'

export const CertificationBadge = ({
  children,
  className,
  ...restOfProps
}) => {
  return (
    <StyledCertificationBadge
      className={className}
      {...pick(restOfProps)}
    >
      {children}
    </StyledCertificationBadge>
  )
}

CertificationBadge.propTypes = {
  /**
   * Component children
   */
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]),

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string
}
