import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { StyledImage } from './Image.styles'

export const Image = ({
  alt,
  src,
  srcSet,
  ...restOfProps
}) => {
  return (
    <StyledImage
      alt={alt}
      src={src}
      srcSet={srcSet}
      {...pick(restOfProps)}
    />
  )
}

Image.propTypes = {
  /**
   * Alt tag used to describe image when it fails to load
   */
  alt: PropTypes.string,

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Image path
   */
  src: PropTypes.string,

  /**
   * Styled system props
   */
  ...propTypes.layout,
  ...propTypes.position,
  ...propTypes.space
}
