import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { Image } from 'components/Image'
import { StyledMoviePoster, StyledMoviePosterOverlay } from './MoviePoster.styles'

export const MoviePoster = ({
  alt,
  className,
  hoverable,
  src,
  ...restOfProps
}) => {
  return (
    <StyledMoviePoster
      className={className}
      hoverable={hoverable}
      {...pick(restOfProps)}
    >
      {src && (
        <Image
          alt={alt}
          left={0}
          position='absolute'
          top={0}
          src={src}
        />
      )}
      {hoverable && (
        <StyledMoviePosterOverlay>
          Click for more&nbsp;details
        </StyledMoviePosterOverlay>
      )}
    </StyledMoviePoster>
  )
}

MoviePoster.propTypes = {
  /**
   * Alt tag used to describe image when it fails to load
   */
  alt: PropTypes.string,

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Enables poster hover overlay
   */
  hoverable: PropTypes.bool,

  /**
   * Movie poster image path
   */
  src: PropTypes.string
}
