import { pick } from '@styled-system/props'
import { motion } from 'framer-motion'
import Link from 'next/link'
import PropTypes from 'prop-types'
import React from 'react'

import { Box } from 'components/Box'
import { H4 } from 'components/Heading'
import { MoviePoster } from 'components/MoviePoster'
import { Skeleton } from 'components/Skeleton'
import { Text } from 'components/Text'
import { formatDate } from 'utils/format-date'

export const Movie = ({
  className,
  date,
  id,
  image,
  title,
  ...restOfProps
}) => {
  return (
    <Box
      className={className}
      {...pick(restOfProps)}
    >
      <motion.div
        whileHover={{ y: -8 }}
        whileTap={{ scale: 0.96 }}
      >
        <Link as={`/movie/${id}`} href='/movie/[id]' passHref>
          <a>
            <MoviePoster
              alt={title}
              hoverable
              mb={3}
              src={image}
            />
          </a>
        </Link>
      </motion.div>
      {title && (
        <Link as={`/movie/${id}`} href='/movie/[id]' passHref>
          <a css={{ textDecoration: 'none' }}>
            <H4>{title}</H4>
          </a>
        </Link>
      )}
      {date && <Text color='neutral.4' fontSize={0}>{formatDate(date)}</Text>}
    </Box>
  )
}

export const MovieSkeleton = (props) => {
  return (
    <Box {...props}>
      <MoviePoster mb={4} />
      <Skeleton height={16} mb={4} width='100%' />
      <Skeleton height={12} mb={2} width='64%' />
    </Box>
  )
}

Movie.propTypes = {
  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Movie release date
   */
  date: PropTypes.string,

  /**
   * Unique movie id used to for navigation
   */
  id: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.string
  ]),

  /**
   * Movie poster image path
   */
  image: PropTypes.string,

  /**
   * Movie title
   */
  title: PropTypes.string
}

Movie.defaultProps = {
  date: 'June 5, 2020',
  title: 'Movie title'
}
