/**
 * @NOTE: Add drag support for popups when iframe is loaded as a child
 */
import { X } from '@styled-icons/boxicons-regular'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { Portal } from 'components/Portal'
import { StyledPopup, StyledPopupButton } from './Popup.styles'

export const Popup = ({ children, className, onClose, ...restOfProps }) => {
  return (
    <Portal selector='#popup'>
      <StyledPopup
        className={className}
        {...pick(restOfProps)}
      >
        <StyledPopupButton onClick={onClose}>
          <X />
        </StyledPopupButton>
        {children}
      </StyledPopup>
    </Portal>
  )
}

Popup.propTypes = {
  /**
   * Component children
   */
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]),

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * onClose event
   */
  onClose: PropTypes.func
}
