import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React, { useState } from 'react'

import { StyledSearchField, StyledSearchFieldInput } from './SearchField.styles'

export const SearchField = ({
  className,
  onSubmit,
  placeholder,
  value,
  ...restOfProps
}) => {
  const [inputVal, setInputVal] = useState(value)

  return (
    <StyledSearchField
      className={className}
      onSubmit={(event) => {
        event.preventDefault()

        if (onSubmit) {
          return onSubmit(inputVal)
        }
      }}
      {...pick(restOfProps)}
    >
      <StyledSearchFieldInput
        onChange={(event) => setInputVal(event.target.value)}
        placeholder={placeholder}
        type='search'
        value={inputVal}
      />
    </StyledSearchField>
  )
}

SearchField.propTypes = {
  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * onSubmit event
   */
  onSubmit: PropTypes.func,

  /**
   * Input placeholder text
   */
  placeholder: PropTypes.string,

  /**
   * Input default values
   */
  value: PropTypes.string,

  /**
   * Styled system props
   */
  ...propTypes.layout,
  ...propTypes.space
}

SearchField.defaultProps = {
  value: ''
}
