import propTypes from '@styled-system/prop-types'
import { pick } from '@styled-system/props'
import PropTypes from 'prop-types'
import React from 'react'

import { StyledText } from './Text.styles'

export const Text = ({
  children,
  className,
  ...restOfProps
}) => {
  return (
    <StyledText
      className={className}
      {...pick(restOfProps)}
    >
      {children}
    </StyledText>
  )
}

Text.propTypes = {
  /**
   * Component children
   */
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node
  ]),

  /**
   * Adds in additional class names in addition to what is generated by styled components.
   */
  className: PropTypes.string,

  /**
   * Styled system props
   */
  ...propTypes.color,
  ...propTypes.space,
  ...propTypes.typography
}
